#!/usr/bin/env python3
"""Assert the ML lockfile is a real resolution and not something edited by hand.

roles/ml/files/requirements-ml.txt is the output of one `uv pip compile` run and
only means anything as a whole. Two ways it silently stops being that:

  1. Regenerated without --index-strategy unsafe-best-match. The cu130 index
     carries frozen copies of torch's dependencies and, being the priority
     index, shadows PyPI for every one of them - the same input then resolves
     certifi 2022.12.7 and datasets 1.1.1, with no warning anywhere.
  2. A bot bumps a single pin. Dependabot security updates read the dependency
     graph regardless of .github/dependabot.yml, and GitHub offers no way to
     exclude a manifest path, so this WILL eventually be attempted.

uv records its own invocation in the file header, which is what makes (1)
checkable at all. (2) is only partly checkable - a plausible single-line edit
still needs a human - but the pins and index directives are cheap to verify.

    python3 tests/check_lockfile.py
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
LOCK = REPO / "roles" / "ml" / "files" / "requirements-ml.txt"
SRC = REPO / "roles" / "ml" / "files" / "requirements-ml.in"
MAKEFILE = REPO / "Makefile"

# Flags the resolution is only correct WITH. See the module docstring.
REQUIRED_FLAGS = ("--index-strategy unsafe-best-match", "--emit-index-url")


def main() -> int:
    problems: list[str] = []

    for path in (LOCK, SRC):
        if not path.exists():
            print(f"lockfile: {path.relative_to(REPO)} is missing", file=sys.stderr)
            return 1

    text = LOCK.read_text()
    header = "\n".join(text.splitlines()[:4])

    # 1. The header must record the flags that make the resolution correct.
    for flag in REQUIRED_FLAGS:
        if flag not in header:
            problems.append(
                f"the autogenerated header does not record `{flag}` - this lockfile "
                f"was not produced by `make lock`, and may resolve to years-old "
                f"transitive versions. Regenerate it on a GX10."
            )

    # 2. `make lock` and the header must agree. Catches a flag added to the
    #    Makefile without regenerating, which would otherwise go unnoticed
    #    until the next person ran it and got a large unexplained diff.
    recipe = MAKEFILE.read_text()
    lock_target = recipe.partition("\nlock:")[2].partition("\n.PHONY")[0]
    for flag in REQUIRED_FLAGS:
        if flag in lock_target and flag not in header:
            problems.append(f"`make lock` passes `{flag}` but the lockfile was built without it")
        if flag in header and flag not in lock_target:
            problems.append(f"the lockfile was built with `{flag}` but `make lock` no longer passes it")

    # 3. Both index directives must survive into the lockfile, or it is
    #    uninstallable - +cu130 does not exist on PyPI.
    for directive in ("--index-url https://pypi.org/simple",
                      "--extra-index-url https://download.pytorch.org/whl/cu130"):
        if directive not in text:
            problems.append(f"missing index directive: {directive}")

    # 4. torch must carry the local version. A bare `torch==x.y.z` means the
    #    PyPI wheel won, which imports fine and then dies at the first kernel
    #    launch with "no kernel image is available".
    torch = re.search(r"^torch==(\S+)$", text, re.M)
    if not torch:
        problems.append("torch is not pinned in the lockfile")
    elif "+cu130" not in torch.group(1):
        problems.append(
            f"torch is pinned to {torch.group(1)}, without the +cu130 local version - "
            f"that is the PyPI wheel, which has no sm_121 kernels"
        )

    # 5. Every requirement must be pinned exactly. A `>=` here means the next
    #    provision resolves something different, which is the whole thing this
    #    file exists to prevent.
    unpinned = [
        ln for ln in text.splitlines()
        if ln and not ln.startswith(("#", " ", "-")) and "==" not in ln
    ]
    if unpinned:
        problems.append(f"not exactly pinned: {', '.join(unpinned[:5])}")

    for p in problems:
        print(f"lockfile: {p}", file=sys.stderr)
    if problems:
        print("lockfile: regenerate with `make lock` ON A GX10 - do not hand-edit", file=sys.stderr)
        return 1

    pins = len(re.findall(r"^[A-Za-z0-9_.-]+==", text, re.M))
    print(f"lockfile: {pins} pins, torch {torch.group(1)}, resolution flags intact")
    return 0


if __name__ == "__main__":
    sys.exit(main())
