#!/usr/bin/env bash
# Point the harness at one of the models this cluster serves.
#
# dsh reads ONE file - $DSH_HOME/settings.yaml, which compose.yml mounts from
# ./dsh-home. So "switching model" means putting a different file there. That
# is all this script does, plus the one check that is worth doing: ASK THE
# SERVER whether the id in the file is a name it actually answers to.
#
# That check exists because the documented failure here is silent. `models[].id`
# must be the SERVED name (`--served-model-name`), not the HF repo id, and a
# wrong one does not fail at startup - the UI simply returns an error on the
# first message, long after you have stopped thinking about settings.
#
#   ./use.sh                        list what is available, and what is active
#   ./use.sh <workspace>            use the settings shipped for that workspace
#   ./use.sh --port 8891 [--id X]   build one from a RUNNING server instead
#
# The --port form is for the three llama.cpp workspaces, which pass no --alias:
# their id is whatever llama.cpp derived from the GGUF, so this repo cannot
# ship it honestly and asks the server instead.
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"

DEFAULT=vllm-2node-qwen38-flash-next
LIVE=dsh-home/settings.yaml

c_bold=$'\033[1m'; c_dim=$'\033[2m'; c_grn=$'\033[32m'; c_yel=$'\033[33m'; c_off=$'\033[0m'
[[ -t 1 ]] || { c_bold=; c_dim=; c_grn=; c_yel=; c_off=; }

die() { echo "use.sh: $*" >&2; exit 1; }

# A read loop rather than `sed 's/^/  /'` - same output, and shellcheck's
# SC2001 is a `make check` failure in this repo, not a suggestion.
indent() { local pad=$1 line; while IFS= read -r line; do printf '%s%s\n' "$pad" "$line"; done; }

available() { local f; for f in settings/*.yaml; do basename "$f" .yaml; done; }

# The port and id a settings file declares. Deliberately grep and not a YAML
# parser: these files are generated by this workspace in one fixed shape, and
# adding a python dependency to a script whose whole job is `cp` is not a trade
# worth making.
field_port() { sed -n 's#.*baseURL: http://127\.0\.0\.1:\([0-9]\+\)/v1.*#\1#p' "$1" | head -1; }
field_id()   { sed -n 's/^ *- id: *//p' "$1" | head -1; }

# What a server on this port says it serves, one id per line. Empty (and
# exit 0) if nothing is listening - "not running yet" is a normal state here,
# not an error: you may well be configuring the harness before you start the
# model.
served_ids() {
    curl -sf --max-time 3 "http://127.0.0.1:$1/v1/models" 2>/dev/null \
        | grep -o '"id" *: *"[^"]*"' | sed 's/.*: *"//; s/"$//' || true
}

verify() {  # $1 = settings file; warns, and only fails on a real contradiction
    local f=$1 port id ids
    port=$(field_port "$f"); id=$(field_id "$f")
    [[ -n $port && -n $id ]] || die "$f declares no baseURL port or no model id"
    # A provider that is defined but not SELECTED leaves dsh on its shipped
    # deepseek-official default, which fails with MISSING_CREDENTIAL rather
    # than falling back to the one provider that is configured.
    grep -q '^agent-default-model:' "$f" \
        || echo "${c_yel}warn${c_off}  $f sets no agent-default-model - dsh will stay on deepseek-official" >&2
    ids=$(served_ids "$port")
    if [[ -z $ids ]]; then
        echo "${c_yel}note${c_off}  nothing answering on :$port yet - start it first:"
        echo "      ws up $(basename "$f" .yaml)"
        return 0
    fi
    if grep -qxF "$id" <<<"$ids"; then
        echo "${c_grn}ok${c_off}    :$port is serving \"$id\""
        return 0
    fi
    echo "${c_yel}warn${c_off}  :$port is up but does NOT serve \"$id\". It serves:" >&2
    indent '        ' <<<"$ids" >&2
    echo "      fix the id in $f, or use: ./use.sh --port $port" >&2
    return 0
}

cmd_list() {
    local n f active=""
    [[ -f $LIVE ]] && for f in settings/*.yaml; do
        cmp -s "$f" "$LIVE" && { active=$(basename "$f" .yaml); break; }
    done
    printf '%s%-38s %-6s %s%s\n' "$c_bold" WORKSPACE PORT MODEL "$c_off"
    for n in $(available); do
        f="settings/$n.yaml"
        printf '%s%-38s %-6s %s%s\n' \
            "$([[ $n == "$active" ]] && printf '%s' "$c_grn")" \
            "$n" "$(field_port "$f")" "$(field_id "$f")" "$c_off"
    done
    echo
    if [[ -n $active ]]; then
        echo "active: ${c_grn}$active${c_off}"
        verify "$LIVE"
    elif [[ -f $LIVE ]]; then
        echo "active: ${c_dim}a hand-written $LIVE (matches none of the above)${c_off}"
        verify "$LIVE"
    else
        echo "active: ${c_yel}none${c_off} - $LIVE does not exist, so dsh has no provider."
        echo "        ./use.sh $DEFAULT"
    fi
}

# THE WEB UI WRITES BACK INTO settings.yaml. Observed: it appends
# `ui-onboarding: welcomeNoticeVersion` after a first visit, and the Models
# page is documented to persist through the same settings service. So a switch
# is not a pure `cp` onto a file only this script owns - it drops whatever the
# UI put there. That is survivable (dsh rewrites its own preferences) but it
# should never be SILENT, so the outgoing file is kept and the lost top-level
# keys are named.
keep_outgoing() {
    [[ -f $LIVE ]] || return 0
    cp "$LIVE" "$LIVE.prev"
    local lost
    lost=$(comm -23 <(top_keys "$LIVE") <(top_keys "$1"))
    [[ -n $lost ]] || return 0
    echo "${c_dim}kept  $LIVE.prev - these top-level keys are not in the new file:${c_off}"
    indent '        ' <<<"$lost"
}

top_keys() { sed -n 's/^\([A-Za-z][A-Za-z0-9_-]*\):.*/\1/p' "$1" | sort -u; }

cmd_use() {
    local n=$1 f="settings/$1.yaml"
    [[ -f $f ]] || { echo "use.sh: no settings for '$n'. available:" >&2
                     available | indent '  ' >&2; exit 1; }
    mkdir -p dsh-home
    keep_outgoing "$f"
    cp "$f" "$LIVE"
    echo "wrote $LIVE from $f"
    verify "$LIVE"
    echo
    echo "restart the harness for it to be read:  ws down deepseek-harness && ws up deepseek-harness"
}

# Build a settings file for a server this repo ships no id for. The id comes
# from the server, never from a guess - which is the entire point.
cmd_port() {
    local port=$1 id=${2:-} ids
    ids=$(served_ids "$port")
    [[ -n $ids ]] || die "nothing answering on http://127.0.0.1:$port/v1/models - start the server first"
    if [[ -z $id ]]; then
        id=$(head -1 <<<"$ids")
        [[ $(wc -l <<<"$ids") -eq 1 ]] || {
            echo "use.sh: :$port serves more than one model - pass --id:" >&2
            indent '  ' <<<"$ids" >&2; exit 1; }
    elif ! grep -qxF "$id" <<<"$ids"; then
        echo "use.sh: :$port does not serve \"$id\". It serves:" >&2
        indent '  ' <<<"$ids" >&2; exit 1
    fi
    mkdir -p dsh-home
    [[ -f $LIVE ]] && cp "$LIVE" "$LIVE.prev"
    cat > "$LIVE" <<EOF
# Generated by use.sh --port $port on $(date -Is).
# The id below was read from the RUNNING server, not guessed.
llm-pi-ai:
  providers:
    gx10:
      apiKeyEnv: LOCAL_API_KEY
      api: openai-completions
      baseURL: http://127.0.0.1:$port/v1
      models:
        - id: $id

# Defining a provider does not SELECT one. Without this, dsh keeps its shipped
# default of deepseek-official/deepseek-flash and asks for DEEPSEEK_API_KEY.
agent-default-model:
  provider: gx10
  model: $id
EOF
    echo "wrote $LIVE  ->  :$port serving \"$id\""
    echo
    echo "restart the harness for it to be read:  ws down deepseek-harness && ws up deepseek-harness"
}

main() {
    local port="" id=""
    case ${1:-} in
        "")            cmd_list; return 0 ;;
        -h|--help)     sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; return 0 ;;
        --port)
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --port) port=${2:-}; shift 2 ;;
                    --id)   id=${2:-};   shift 2 ;;
                    *)      die "unexpected argument '$1'" ;;
                esac
            done
            [[ $port =~ ^[0-9]+$ ]] || die "--port needs a port number"
            cmd_port "$port" "$id"; return 0 ;;
        -*)            die "unknown option '$1'. try: ./use.sh --help" ;;
        *)             cmd_use "$1"; return 0 ;;
    esac
}

main "$@"
